export const CARD_OPTIONS = [
  {
    name: 'Fibonacci',
    cards: [
      { display: '0', value: 0 },
      { display: '1', value: 1 },
      { display: '2', value: 2 },
      { display: '3', value: 3 },
      { display: '5', value: 5 },
      { display: '8', value: 8 },
      { display: '13', value: 13 },
      { display: '21', value: 21 },
      { display: '34', value: 34 },
      { display: '55', value: 55 },
      { display: '89', value: 89 },
      { display: '?', value: '?' },
    ],
  },
  {
    name: 'Modified Fibonacci',
    cards: [
      { display: '0', value: 0 },
      { display: '1/2', value: 0.5 },
      { display: '1', value: 1 },
      { display: '2', value: 2 },
      { display: '3', value: 3 },
      { display: '5', value: 5 },
      { display: '8', value: 8 },
      { display: '13', value: 13 },
      { display: '20', value: 20 },
      { display: '40', value: 40 },
      { display: '100', value: 100 },
      { display: '?', value: '?' },
    ],
  },
  {
    name: 'T-Shirts',
    cards: [
      { display: 'XXS', value: 1 },
      { display: 'XS', value: 2 },
      { display: 'S', value: 3 },
      { display: 'M', value: 4 },
      { display: 'L', value: 5 },
      { display: 'XL', value: 6 },
      { display: 'XXL', value: 7 },
      { display: '?', value: '?' },
    ],
  },
  {
    name: 'Power of 2s',
    cards: [
      { display: '0', value: 0 },
      { display: '1', value: 1 },
      { display: '2', value: 2 },
      { display: '4', value: 4 },
      { display: '8', value: 8 },
      { display: '16', value: 16 },
      { display: '32', value: 32 },
      { display: '64', value: 64 },
      { display: '?', value: '?' },
    ],
  },
]
